version: "3.8"

services:
  web:
    build: ./
    container_name: todo_web
    restart: always
    command: bash entrypoint.sh
    env_file:
      - ./.env.dev
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image:  postgres:latest
    container_name: todo_db
    restart: always
    env_file:
      - ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    container_name: todo_redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'

  nginx:
    build: ./nginx
    container_name: todo_nginx
    restart: on-failure
    ports:
      - '80:80'
    volumes:
      - ./static:/static
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data: