# Generated by Django 4.0 on 2022-01-14 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of your task', max_length=255)),
                ('content', models.TextField(blank=True, help_text='Enter your task', max_length=1000, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='auth.user')),
            ],
            options={
                'ordering': ['-date_create'],
            },
        ),
    ]
